//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ModMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [=----------------------------------------------------------------------=]
        ///    __  __           __     _____ _                   __                
        ///   / / / /__  ____ _/ /_   / ___/(_)___ _____  ____ _/ /___  __________ 
        ///  / /_/ / _ \/ __ `/ __/   \__ \/ / __ `/ __ \/ __ `/ __/ / / / ___/ _ \
        /// / __  /  __/ /_/ / /_    ___/ / / /_/ / / / / /_/ / /_/ /_/ / /  /  __/
        ////_/ /_/\___/\__,_/\__/   /____/_/\__, /_/ /_/\__,_/\__/\__,_/_/   \___/ 
        ///                                /____/                             [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Banner1 {
            get {
                return ResourceManager.GetString("Banner1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     __  ___          __                        __            
        ///   /  |/  /___  ____/ /  _____________  ____ _/ /_____  _____
        ///  / /|_/ / __ \/ __  /  / ___/ ___/ _ \/ __ `/ __/ __ \/ ___/
        /// / /  / / /_/ / /_/ /  / /__/ /  /  __/ /_/ / /_/ /_/ / /    
        ////_/  /_/\____/\__,_/   \___/_/   \___/\__,_/\__/\____/_/     
        ///[=----------------------------------------------------------------------=].
        /// </summary>
        internal static string Banner2 {
            get {
                return ResourceManager.GetString("Banner2", resourceCulture);
            }
        }
    }
}
